"""user-role change

Revision ID: 266ac4dab4cd
Revises: edeb7fd619fd
Create Date: 2023-04-27 18:21:30.541054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '266ac4dab4cd'
down_revision = 'edeb7fd619fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
